name: Run 
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          token: ${{ secrets.AUTIFY_TOKEN }} 
          id: ${{ secrets.AUTIFY_TESTPLAN_ID }}
